version: '2'

services: 
  spring-docker-service:
    image: spring-docker-service
    build:
      context: ./anima_newsletter_backend
      dockerfile: ./Dockerfile
    ports:
      - 7070:8080
    environment:
      - CATALINA_OPTS=-Dspring.profiles.active=container
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=test  
      - DATABASE_PORT=3306
  angular-docker-service:
    image: angular-docker-service
    build:
      context: ./anima_newsletter_front-end
      dockerfile: ./Dockerfile
    ports:
      - 4200:80