version: '2.1'

services: 
  docker-mysql:
    container_name: docker-mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=anima_newsletter
      - MYSQL_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 20
    ports:
    - 3306:3306
  docker-liquidbase:
    container_name: docker-liquibase
    image: abfut-local-docker-liquibase
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      docker-mysql: 
        condition: service_healthy
